### ISSUE TITLE
update of the better folliage config file

### ISSUE THREAD

**Issue by 0Navis0** [octarine-noise/BetterFoliage#73]
I noticed that the better foliage configuration is totally outdated, all the mod class changed. So after some searshs and the help of my friend WanionCane (Unidict mod owner), I made a new configuration including all the new class name of all the mod I know and use for the 1.9.4 and 1.10.2. I didn't test everything and some things could not work properly or have unwanted behaviour. It incudes the support for the grass, dirt, sand, leaves, logs, crops, lilypad and cactus for the following mod : 
- Aether
- BiomesOPlenty
- HighLands
- PlantMegaPack
- TinkersConstruct
- Forestry
- Thaumcraft
- ThaumicBases
- BloodArsenal
- Botania
- AbyssalCraft
- EvilCraft
- IntegratedDynamics
- IndustrialCraft
- TechReborn
- Calculator
- HarvestCraft
- Terraqueous
- ExtraUtilities
- RandomThings
- ActuallyAdditions
- SugiForest

http://pastebin.com/bV4ATh1z

**Comment by 0Navis0** [comment]
The flowering oak leave from BiomeOPlenty, the rubber leaves from TechReborn, and the fallen leaves from SugiForest aren't recognized by better foliage for the dens foliage and falling leaves effects, while the moving wind effect works nice.

**Comment by octarine-noise** [comment]
Thanks for the config. I'll integrate it in the next release, and also take a look at the problematic leaves too.

**Comment by octarine-noise** [comment]
I waded through the list. I merged the changes, and threw out a lot of the file - it turns out many entries were redundant, as the vanilla leaves entry covered them already.
TechReborn is not exactly as easy as I thought, and will require rewriting certain things that I have been putting off for a while.

Next release, when it comes, will have the new defaults.

**Comment by 0Navis0** [comment]
Hm ok nice to hear. ;)

**Comment by ghost** [comment]
After updating to Better Foliage 2.1.1 - I noticed the following behaviour:
1. I deleted the config file, so BF generated a new one.
2. I compared the new config file with my backup.
3. A lot of sections like "roundlogs" (with lower L) are gone and replaced by e.g. "roundLogs". That's ok.
4. I disabled roundLog by setting enabled to false.
5. When now starting the game, it puts the old sections back in, so for example of roundLogs it looks like this:

```
roundLogs {
    B:enabled=true
    I:distance=1000
    D:radiusSmall=0.25
    D:radiusLarge=0.44
    D:dimming=0.7
    B:connectSolids=false
    B:lenientConnect=true
    B:connectPerpendicular=true
    B:connectGrass=true
    B:defaultY=false
    D:zProtection=0.99
}


roundlogs {
    B:connectGrass=true
    B:connectPerpendicular=true
    B:connectSolids=false
    B:defaultY=false
    D:dimming=0.7
    I:distance=1000
    B:enabled=false
    B:lenientConnect=true
    D:radiusLarge=0.44
    D:radiusSmall=0.25
    D:zProtection=0.99
}
```

As you can see, the roundlogs are enabled again, and they stay enabled, meaning I can't disable them anymore.

I think this is not the intended behaviour...

**Comment by octarine-noise** [comment]
No, definitely not. It's a regression to a problem I fixed before. I'll try to get to the bottom of this, just as soon as I can reproduce it in the dev environment.

**Comment by ghost** [comment]
I tested with only Forge (2090) and Better Foliage installed, and the behavior is 100% reproducible.

**Comment by 0Navis0** [comment]
I add another problem. The wind moving effect doesn't work with all BiomesOPlenty, Botania, Terraqueous, Harverscraft, Actually Additions, Random Things and Extra Utilities bushes and flowers. 
And the dense folliage still doesn't work with IndustrialCraft rubber tree leaves and BiomesOPlenty flowering oak leaves.

**Comment by quasitonality** [comment]
Had exactly the same problem mankra described, using Forge 12.18.1.2046 and Better Foliage 2.1.1.

Sections labeled in the format _firstSecond_ are duplicated in the format _firstsecond_; changes made on the in-game menu are saved only to the section labeled _firstsecond_, but when the game is relaunched the settings from _firstSecond_ are used. Additionally, _firstSecond_ is reset to default values every time the game is launched, overwriting any manual out-of-game changes. Sections labeled in the format _first_, however, behave as expected.

Upon deleting the config file and testing Better Foliage _2.1.0_ with the same version of forge, the config file behaves normally; there are no longer any sections in the _firstSecond_ format, but only _firstsecond_, and changes to the config are persistent from both in and out of game.

**Comment by ghost** [comment]
Quote from the Forge changelog:

> Build 2094:
>   mmehnert:
>       caseSensitiveCustomCategories must be set before loading the
>       configuration file. (#3269)
>       Otherwise one set with categories in lowercase letters and on case
>       sensitive

I updated to Forge build 2094 and the config file of Better Foliage 2.1.1 now generates correctly.

**Comment by octarine-noise** [comment]
Aha, very good. I suspected foul play from Forge, but didn't have the time to track it down.

I consider this one fixed, then. Just use Forge 2094 or later.

**Comment by 0Navis0** [comment]
I update again the better folliage config. ;)
http://pastebin.com/zsJwdvg2

**Comment by quasitonality** [comment]
Was it broken again?

**Comment by 0Navis0** [comment]
Nah it's for adding support for more mods. ;)
